# Generated by Django 5.2.8 on 2025-11-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Contact Support', max_length=200)),
                ('description', models.TextField(default='Our support team is available 24/7 to assist you. Reach out for any queries, technical support, or partnership discussions.')),
                ('image', models.ImageField(default='images/notes/contact.jpg', upload_to='cards/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Page Card',
                'verbose_name_plural': 'Contact Page Card',
            },
        ),
        migrations.CreateModel(
            name='FranchisePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Franchise Opportunities', max_length=200)),
                ('description', models.TextField(default='Expand your business portfolio with our proven franchise model. Comprehensive training and ongoing support included.')),
                ('image', models.ImageField(default='images/notes/franchise.jpg', upload_to='cards/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Franchise Page Card',
                'verbose_name_plural': 'Franchise Page Card',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Home Services', max_length=200)),
                ('description', models.TextField(default='Professional home maintenance and repair services to keep your living space comfortable and well-maintained throughout the year.')),
                ('image', models.ImageField(default='images/notes/home.jpg', upload_to='cards/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page Card',
                'verbose_name_plural': 'Home Page Card',
            },
        ),
        migrations.CreateModel(
            name='PackagesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Premium Packages', max_length=200)),
                ('description', models.TextField(default='Choose from our exclusive packages designed for different needs. All packages include premium features and dedicated support.')),
                ('image', models.ImageField(default='images/notes/packages.jpg', upload_to='cards/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Packages Page Card',
                'verbose_name_plural': 'Packages Page Card',
            },
        ),
    ]
