# Generated by Django 5.2.8 on 2025-11-14 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_packageplan_packagefeature_packagedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarWashPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Essential Care', max_length=200)),
                ('description', models.TextField(default="Perfect for maintaining your vehicle's appearance with professional exterior and interior care.")),
                ('ideal_for', models.CharField(default='Regular maintenance, monthly touch-ups', max_length=300)),
                ('button_text', models.CharField(default='Select Package', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Car Wash Package',
                'verbose_name_plural': 'Car Wash Packages',
            },
        ),
        migrations.RemoveField(
            model_name='packagefeature',
            name='package',
        ),
        migrations.CreateModel(
            name='PackageInclude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='includes', to='dashboard.carwashpackage')),
            ],
            options={
                'verbose_name': 'Package Include',
                'verbose_name_plural': 'Package Includes',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='PackageDetail',
        ),
        migrations.DeleteModel(
            name='PackageFeature',
        ),
        migrations.DeleteModel(
            name='PackagePlan',
        ),
    ]
