# Generated by Django 5.2.8 on 2025-11-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_galleryitem_delete_galleryimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='franchisepage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='packagespage',
            options={},
        ),
        migrations.AddField(
            model_name='contactpage',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='cards/videos/'),
        ),
        migrations.AddField(
            model_name='franchisepage',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='franchisepage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='cards/videos/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='cards/videos/'),
        ),
        migrations.AddField(
            model_name='packagespage',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='packagespage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='cards/videos/'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='description',
            field=models.TextField(default="Contact us for any inquiries or support. We're here to help you."),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='title',
            field=models.CharField(default='Get In Touch', max_length=200),
        ),
        migrations.AlterField(
            model_name='franchisepage',
            name='description',
            field=models.TextField(default='Join our growing network of franchises and be part of our success story.'),
        ),
        migrations.AlterField(
            model_name='packagespage',
            name='description',
            field=models.TextField(default='Explore our carefully crafted packages designed to meet your every need.'),
        ),
        migrations.AlterField(
            model_name='packagespage',
            name='title',
            field=models.CharField(default='Our Packages', max_length=200),
        ),
    ]
