# Generated by Django 5.2.8 on 2025-11-17 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_contactpage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseInstaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('location', models.CharField(max_length=300)),
                ('address', models.TextField()),
                ('shop_open_time', models.TimeField()),
                ('shop_close_time', models.TimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='installers/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'franchise_installers',
                'ordering': ['-created_at'],
            },
        ),
    ]
