# Generated by Django 5.2.8 on 2025-11-17 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_franchiseinstaller'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchiseinstaller',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='installers/banner/'),
        ),
        migrations.AddField(
            model_name='franchiseinstaller',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchiseinstaller',
            name='map_url',
            field=models.URLField(blank=True, help_text='Google Maps URL for the installer location', null=True),
        ),
        migrations.AddField(
            model_name='franchiseinstaller',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='franchiseinstaller',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='installers/profile/'),
        ),
    ]
