# Generated by Django 5.2.8 on 2025-11-17 09:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_franchiseinstaller_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchiseinstaller',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
