# Generated by Django 5.2.8 on 2026-01-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_franchiseinstaller_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwashpackage',
            name='category',
            field=models.CharField(blank=True, help_text="Sub-category like 'Glossy', 'Matte', 'Dazzling' for PPF, etc.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carwashpackage',
            name='material',
            field=models.CharField(blank=True, help_text='Material information if applicable', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carwashpackage',
            name='saloon_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price for Saloon/Sedan', max_digits=10),
        ),
        migrations.AddField(
            model_name='carwashpackage',
            name='service_type',
            field=models.CharField(choices=[('interior', 'Interior Detailing'), ('exterior', 'Exterior Detailing'), ('ppf', 'Paint Protection Film (PPF)'), ('ceramic', 'Ceramic Coating'), ('wash', 'Car Wash'), ('window_film', 'Window Film')], default='wash', max_length=50),
        ),
        migrations.AddField(
            model_name='carwashpackage',
            name='suv_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price for SUV/4x4', max_digits=10),
        ),
        migrations.AddField(
            model_name='carwashpackage',
            name='warranty',
            field=models.CharField(blank=True, help_text='Warranty duration or terms', max_length=100, null=True),
        ),
    ]
