# Generated by Django 5.2.8 on 2026-01-31 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_carwashpackage_category_carwashpackage_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('interior', 'Interior Detailing'), ('exterior', 'Exterior Detailing'), ('ppf', 'Paint Protection Film (PPF)'), ('ceramic', 'Ceramic Coating'), ('wash', 'Car Wash'), ('window_film', 'Window Film')], default='wash', max_length=50)),
                ('name', models.CharField(help_text='Sub-category name (e.g., Glossy, Matte, Standard)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
            },
        ),
        migrations.RemoveField(
            model_name='carwashpackage',
            name='service_type',
        ),
        migrations.AlterField(
            model_name='carwashpackage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='dashboard.servicecategory'),
        ),
    ]
