# Generated by Django 5.2.8 on 2026-01-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_servicecategory_remove_carwashpackage_service_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='service_type',
            field=models.CharField(choices=[('ppf', 'Paint Protection Film (PPF)'), ('window_tinting', 'Window Tinting'), ('borophene', 'Borophene Coating'), ('graphene', 'Graphene Coating'), ('ceramic', 'Ceramic Coating'), ('interior', 'Interior Detailing')], default='wash', max_length=50),
        ),
    ]
